site_name: Bachelor of Computer Science
site_url: https://yifen9.github.io/UNITN.BSc

repo_name: UNITN BSc
repo_url: https://github.com/yifen9/UNITN.BSc

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    - scheme: default
      primary: custom   # Custom color defined in extra CSS
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/logo.jpg       # UniTrento logo image (recommend PNG with transparency)
  favicon: assets/favicon.png
  features:
    - content.code.copy
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest

extra:
  social:
    - icon: fontawesome/solid/blog
      link: https://yifen9.github.io
    - icon: fontawesome/solid/graduation-cap
      link: mailto:<yifeng.li@studenti.unitn.it>
    - icon: fontawesome/brands/yandex
      link: mailto:<yifen9@yandex.com>
    - icon: fontawesome/brands/github
      link: https://github.com/yifen9
    - icon: fontawesome/brands/telegram
      link: https://t.me/yifen9

# Custom CSS and JS for layout + logo effects
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css
  - overrides/extra.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - overrides/extra.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Markdown features
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - meta
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - toc:
      permalink: true

# Plugins
plugins:
  - awesome-pages
  - search

nav:
  - Home:
    - index.md