-- The employees listed in the previous query have been selected for a special training program.
-- Northwind Traders’ Megadirector – your boss – would like to know more about these employees.
-- Provide a detailed report for him: in each row of the report, list
--   ▶ the employee IDs as found in the previous query,
--   ▶ a country the employee has shipped to,
--   ▶ the average number of days it took for the employee to ship an order to that country
--   ▶ how many distinct products the employee has shipped to that country
-- Make sure rows with incomplete data are stripped out.