services:
  unitn-l31-lab:
    image: ghcr.io/yifen9/unitn-l31-lab
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: unitn-l31-lab
    working_dir: /workspace
    volumes:
      - "..:/workspace"
    command: >
      bash -c "
        exec sleep infinity
      "
  unitn-l31-lab-db:
    image: postgres
    container_name: unitn-l31-lab-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - "postgresql:/var/lib/postgresql"
  unitn-l31-lab-db-pgadmin:
    image: dpage/pgadmin4
    container_name: unitn-l31-lab-db-pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=mail@yifen9.li
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - 5050:80
    volumes:
      - "pgadmin:/var/lib/pgadmin"

volumes:
  postgresql:
  pgadmin: