name: image

on:
  push:
    branches:
      - "main"
    paths:
      - "Dockerfile"
      - "/ops/apt.txt"
      - ".github/workflows/image.yaml"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: docker/setup-buildx-action@master
      - uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@master
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/unitn-l31-lab:latest
            ghcr.io/${{ github.repository_owner }}/unitn-l31-lab:${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/unitn-l31-lab:cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/unitn-l31-lab:cache,mode=max